### ISSUE TITLE
 MinecraftLauncher-core for 1.19.3

### ISSUE THREAD

**Issue by AnonymeUSB** [Pierce01/MinecraftLauncher-core#101]
Hello,
would it be possible to add the new versions (up to 1.19.3) ? Indeed, when I go to my code and change the version of the game by a version more recent than "1.16", the program crashes at launch.

**Comment by AnonymeUSB** [comment]
Log : 
```
[MCLC]: Using Java version 1.8.0_51 64-bit
[MCLC]: Parsed version from version manifest
[MCLC]: Attempting to download Minecraft version jar
[MCLC]: Downloaded version jar and wrote version json
[MCLC]: Collected class paths
[MCLC]: Using ; to separate class paths
[MCLC]: Attempting to download assets
[MCLC]: Downloaded assets
[MCLC]: Set launch options
[MCLC]: Launching with arguments -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Djava.library.path=C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft -Xmx6G -Xms4G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -cp C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\google\code\gson\gson\2.10\gson-2.10.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\github\oshi\oshi-core\6.2.2\oshi-core-6.2.2.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\google\guava\guava\31.1-jre\guava-31.1-jre.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\authlib\3.16.29\authlib-3.16.29.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\blocklist\1.0.10\blocklist-1.0.10.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\brigadier\1.0.18\brigadier-1.0.18.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\datafixerupper\5.0.28\datafixerupper-5.0.28.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\javabridge\2.0.25\javabridge-2.0.25.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\logging\1.1.1\logging-1.1.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\patchy\2.2.10\patchy-2.2.10.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\ibm\icu\icu4j\71.1\icu4j-71.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\text2speech\1.13.9\text2speech-1.13.9.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\com\mojang\text2speech\1.13.9\text2speech-1.13.9-natives-windows.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-buffer\4.1.82.Final\netty-buffer-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-codec\4.1.82.Final\netty-codec-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-common\4.1.82.Final\netty-common-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-resolver\4.1.82.Final\netty-resolver-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-transport-classes-epoll\4.1.82.Final\netty-transport-classes-epoll-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-handler\4.1.82.Final\netty-handler-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-transport-native-unix-common\4.1.82.Final\netty-transport-native-unix-common-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\io\netty\netty-transport\4.1.82.Final\netty-transport-4.1.82.Final.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\net\java\dev\jna\jna-platform\5.12.1\jna-platform-5.12.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\net\java\dev\jna\jna\5.12.1\jna-5.12.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\apache\httpcomponents\httpcore\4.4.15\httpcore-4.4.15.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\apache\logging\log4j\log4j-api\2.19.0\log4j-api-2.19.0.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\apache\logging\log4j\log4j-core\2.19.0\log4j-core-2.19.0.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\apache\logging\log4j\log4j-slf4j2-impl\2.19.0\log4j-slf4j2-impl-2.19.0.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\joml\joml\1.10.5\joml-1.10.5.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\it\unimi\dsi\fastutil\8.5.9\fastutil-8.5.9.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.1\lwjgl-glfw-3.3.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.1\lwjgl-glfw-3.3.1-natives-windows-x86.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.1\lwjgl-glfw-3.3.1-natives-windows.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.1\lwjgl-jemalloc-3.3.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.1\lwjgl-jemalloc-3.3.1-natives-windows.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.1\lwjgl-jemalloc-3.3.1-natives-windows-x86.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.1\lwjgl-openal-3.3.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.1\lwjgl-openal-3.3.1-natives-windows.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.1\lwjgl-openal-3.3.1-natives-windows-x86.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.1\lwjgl-opengl-3.3.1.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.1\lwjgl-opengl-3.3.1-natives-windows.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.1\lwjgl-opengl-3.3.1-natives-windows-x86.jar;C:\Users\User\Documents\EarthAwakening\Launcher\EarthAwakening\Selvania\Selvania-Launcher\minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.1\lwjgl-stb-3.3.1.jar;C:\Users\User\Documents\EarthAwak        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)        at java.lang.ClassLoader.loadClass(Unknown Source)        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"```

**Comment by Pierce01** [comment]
Hey there, this error means you're using the wrong java version. 1.19 requires at least java 17
