### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by zaralX** [Pierce01/MinecraftLauncher-core#125]
About a year ago I used the MinecraftLauncher-core code as the basis for my launcher (To make quite a few changes for myself) everything worked well but recently I decided to return to the launcher and ran into problems:

Missing: D:\test\minecast\packs\test\libraries\net\minecraftforge\forge\1.20.1-47.3.0\forge-1.20.1-47.3.0-client.jar
Missing: D:\test\minecast\packs\test\libraries\net\minecraft\client\1.20.1-20230612.114412\client-1.20.1-20230612.114412-slim.jar

I upgraded to ForgeWrapper 1.6.0 (This may be the problem)
Please tell me what has changed during this time, I haven’t been able to find a solution for several hours now, these libraries just won’t download.

P.S. All other libraries/assets and so on are downloaded successfully

Full error:
```
Missing: D:\test\minecast\packs\test\libraries\net\minecraft\client\1.20.1-20230612.114412\client-1.20.1-20230612.114412-slim.jar
Some extra libraries are missing! Running the installer to generate them now.

JVM info: Oracle Corporation - 17.0.10 - 17.0.10+11-LTS-240
java.net.preferIPv4Stack=true

Exception in thread "main" java.lang.reflect.InvocationTargetException

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:51)
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.installer.actions.PostProcessors.process(java.io.File, java.io.File, java.io.File, java.io.File)'
        at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1$ClientInstall4MultiMC.run(InstallerV1.java:35)
        at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1.runClientInstall(InstallerV1.java:20)

        at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:26)
        ... 5 more

Closed. Code: 1
```

**Comment by Pierce01** [comment]
`Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.installer.actions.PostProcessors.process(java.io.File, java.io.File, java.io.File, java.io.File)'` makes me think the installer jar is outdated. If it works on older versions of ForgeWrapper, then it's 100% the reason. re https://github.com/ZekerZhayard/ForgeWrapper/commit/3c6712d64a42e4ec200909912e72749499aaca79

I'd recommend getting an updated installer jar from the forge website. If that doesn't change anything, could you post your launcher options and MCLC version?

**Comment by zaralX** [comment]
I'm an idiot, I thought I updated forge-wrapper but I didn't
