### ISSUE TITLE
OSX native issues

### ISSUE THREAD

**Issue by Pierce01** [Pierce01/MinecraftLauncher-core#16]
Not sure why, but it seems 1.14.2 crashes due to missing natives. I'm going to assume I just didnt parse correctly, but I'll look into it when I get the chance

```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 7/23/19 10:20 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
    at org.lwjgl.system.Library.loadSystem(Library.java:147)
    at org.lwjgl.system.Library.loadSystem(Library.java:67)
    at org.lwjgl.system.Library.<clinit>(Library.java:50)
    at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
    at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:61)
    at cud.a(SourceFile:106)
    at com.mojang.blaze3d.platform.GLX.initGlfw(SourceFile:191)
    at cvk.au(SourceFile:459)
    at cvk.b(SourceFile:395)
    at net.minecraft.client.main.Main.main(SourceFile:154)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at org.lwjgl.system.Library.loadSystem(Library.java:147)
    at org.lwjgl.system.Library.loadSystem(Library.java:67)
    at org.lwjgl.system.Library.<clinit>(Library.java:50)
    at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
    at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:61)
    at cud.a(SourceFile:106)
    at com.mojang.blaze3d.platform.GLX.initGlfw(SourceFile:191)
    at cvk.au(SourceFile:459)

-- Initialization --
Details:
Stacktrace:
    at cvk.b(SourceFile:395)
    at net.minecraft.client.main.Main.main(SourceFile:154)

-- System Details --
Details:
    Minecraft Version: 1.14.2
    Operating System: Mac OS X (x86_64) version 10.14.3
    Java Version: 1.8.0_222, AdoptOpenJDK
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
    Memory: 885714168 bytes (844 MB) / 1029177344 bytes (981 MB) up to 6347554816 bytes (6053 MB)
    JVM Flags: 4 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitSta...
```

**Comment by Pierce01** [comment]
fixed in b850909
