### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by umitc18** [Pierce01/MinecraftLauncher-core#2]
```
launcher.authenticator.getAuth(username, password).then(function(auth) {
	launcher.core({
		authorization: auth,
		clientPackage: null,
		root: "C:/Users/admin/AppData/Roaming/.minecraft",
		os: "windows",
		version: {
			number: "1.8.8",
			type: "release"
		},
		memory: {
			max: "1024"
		}
	});
});```


C:\Users\admin\Desktop\myDB\node_modules\minecraft-launcher-core\components\authenticator.js:38
                throw new Error("Validation error: " + response.statusMessage);
                ^

Error: Validation error: Forbidden
    at Request._callback (C:\Users\admin\Desktop\myDB\node_modules\minecraft-launcher-core\components\authenticator.js:38:23)
    at Request.self.callback (C:\Users\admin\Desktop\myDB\node_modules\minecraft-launcher-core\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\admin\Desktop\myDB\node_modules\minecraft-launcher-core\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\admin\Desktop\myDB\node_modules\minecraft-launcher-core\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by Pierce01** [comment]
Hey there! Thanks for taking interest in this project. 

Whats `username` and `password` defined as? 

Also make sure you're passing the correct login

**Comment by umitc18** [comment]
I solved the problem but now it's giving me this error: TypeError: Path must be a string. Received undefined

**Comment by Pierce01** [comment]
can you give me the full stack trace (as in the error)? 

I'm pretty sure you're just passing an object instead of a string, though.

**Comment by Pierce01** [comment]
Closing since user hasn't responded. Assuming they've solved it
