### ISSUE TITLE
Unable to launch OptiFine 1.18

### ISSUE THREAD

**Issue by H4kt** [Pierce01/MinecraftLauncher-core#90]
Version json: https://www.toptal.com/developers/hastebin/efedakeqes.json
Note: I changed invalid OptiFine libraries' links to valid ones from our custom server.

Options:
```ts
const otps: ILauncherOptions = {
  root: <root path>,
  version: {
    custom: "OptiFine 1.18"
  },
  authorization: getAuth(),
  memory: {
    min: "4G",
    max: "6G"
  }
};

const getAuth = async (): Promise<IUser> => {
 return {
   access_token: '',
   client_token: '',
   uuid: 'e63d3652-1822-4986-9e87-344f4d340878',
   name: 'H4kt',
   user_properties: undefined,
   meta: {
     type: 'msa',
     demo: false,
   }
 }
}
```

Error log:
```
[MCLC]: MCLC version 3.16.13
[MCLC]: Using Java version 17.0.3.1 64-bit
[MCLC]: Downloaded and extracted natives
[MCLC]: Set native path to C:\Users\H4kt\Desktop\test\natives\1.18
[MCLC]: Detected custom in options, setting custom version file
[MCLC]: Collected class paths
[MCLC]: Using ; to separate class paths
[MCLC]: Attempting to download assets
[MCLC]: Downloaded assets
[MCLC]: Set launch options
[MCLC]: Launching with arguments -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Djava.library
.path=C:\Users\H4kt\Desktop\test\natives\1.18 -Xmx6G -Xms4G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -cp C:\Users\H4kt\Desktop\test\librari
es\com\mojang\blocklist\1.0.6\blocklist-1.0.6.jar;C:\Users\H4kt\Desktop\test\libraries\com\mojang\patchy\2.1.6\patchy-2.1.6.jar;C:\Users\H4kt\Desktop\test\libraries\optifine\launchwrapper
\2.3\launchwrapper-2.3.jar;C:\Users\H4kt\Desktop\test\libraries\com\github\oshi\oshi-core\5.8.2\oshi-core-5.8.2.jar;C:\Users\H4kt\Desktop\test\libraries\net\java\dev\jna\jna\5.9.0\jna-5.9
.0.jar;C:\Users\H4kt\Desktop\test\libraries\net\java\dev\jna\jna-platform\5.9.0\jna-platform-5.9.0.jar;C:\Users\H4kt\Desktop\test\libraries\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0
-beta4.jar;C:\Users\H4kt\Desktop\test\libraries\org\apache\logging\log4j\log4j-slf4j18-impl\2.14.1\log4j-slf4j18-impl-2.14.1.jar;C:\Users\H4kt\Desktop\test\libraries\com\mojang\javabridge
\1.2.24\javabridge-1.2.24.jar;C:\Users\H4kt\Desktop\test\libraries\optifine\OptiFine\1.18_HD_U_H3\OptiFine-1.18_HD_U_H3.jar;C:\Users\H4kt\Desktop\test\libraries\net\sf\jopt-simple\jopt-si
mple\5.0.4\jopt-simple-5.0.4.jar;C:\Users\H4kt\Desktop\test\libraries\io\netty\netty-all\4.1.68.Final\netty-all-4.1.68.Final.jar;C:\Users\H4kt\Desktop\test\libraries\com\ibm\icu\icu4j\69.
1\icu4j-69.1.jar;C:\Users\H4kt\Desktop\test\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\H4kt\Desktop\test\libraries\org\apache\commons\commons-lang3\3.
12.0\commons-lang3-3.12.0.jar;C:\Users\H4kt\Desktop\test\libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar;C:\Users\H4kt\Desktop\test\libraries\commons-io\commons-io\2.11.0
\commons-io-2.11.0.jar;C:\Users\H4kt\Desktop\test\libraries\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;C:\Users\H4kt\Desktop\test\libraries\com\mojang\brigadier\1.0.18\brigad
ier-1.0.18.jar;C:\Users\H4kt\Desktop\test\libraries\com\mojang\datafixerupper\4.0.26\datafixerupper-4.0.26.jar;C:\Users\H4kt\Desktop\test\libraries\com\google\code\gson\gson\2.8.8\gson-2.
8.8.jar;C:\Users\H4kt\Desktop\test\libraries\com\mojang\authlib\3.2.38\authlib-3.2.38.jar;C:\Users\H4kt\Desktop\test\libraries\org\apache\commons\commons-compress\1.21\commons-compress-1.
21.jar;C:\Users\H4kt\Desktop\test\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;C:\Users\H4kt\Desktop\test\libraries\commons-logging\commons-logging\1.2\comm
ons-logging-1.2.jar;C:\Users\H4kt\Desktop\test\libraries\org\apache\httpcomponents\httpcore\4.4.14\httpcore-4.4.14.jar;C:\Users\H4kt\Desktop\test\libraries\org\apache\logging\log4j\log4j-
api\2.14.1\log4j-api-2.14.1.jar;C:\Users\H4kt\Desktop\test\libraries\org\apache\logging\log4j\log4j-core\2.14.1\log4j-core-2.14.1.jar;C:\Users\H4kt\Desktop\test\libraries\org\lwjgl\lwjgl\
3.2.2\lwjgl-3.2.2.jar;C:\Users\H4kt\Desktop\test\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\H4kt\Desktop\test\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-
openal-3.2.2.jar;C:\Users\H4kt\Desktop\test\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\H4kt\Desktop\test\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.
jar;C:\Users\H4kt\Desktop\test\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\H4kt\Desktop\test\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;C:\Users\H4
kt\Desktop\test\libraries\it\unimi\dsi\fastutil\8.5.6\fastutil-8.5.6.jar;C:\Users\H4kt\Desktop\test\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;C:\Users\H4kt\Desktop\te
st\versions\OptiFine 1.18\OptiFine 1.18.jar net.minecraft.launchwrapper.Launch --username H4kt --version 1.18 --gameDir C:\Users\H4kt\Desktop\test --assetsDir C:\Users\H4kt\Desktop\test\assets --assetIndex 1.18 --uuid e63d3652-1822-4986-9e87-344f4d340878 --accessToken  --clientId  --xuid  --userType msa --versionType release
Launched game in 0.73695 min
[02:27:01] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker

[02:27:01] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.VanillaTweaker
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:104) ~[launchwrapper-2.3.jar:2.3]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:122) [launchwrapper-2.3.jar:2.3]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-2.3.jar:2.3]
```

**Comment by AarushX** [comment]
A quick google search finds [this Minecraft Forum](https://www.minecraftforum.net/forums/support/java-edition-support/2947305-unable-to-launch-java-lang-classnotfoundexception) that says your MC files have been corrupted. I suggest checking that 

1. "Optifine 1.18.jar" exists
2. Your custom server libraries are being served 
3. Check out this [issue](https://www.reddit.com/r/Optifine/comments/bvjtth/comment/epsqn39/?utm_source=share&utm_medium=web2x&context=3) and try out different Java versions
4. Make sure you have added [these arguments](https://www.reddit.com/r/Optifine/comments/bvjtth/comment/eqmmlg3/?utm_source=share&utm_medium=web2x&context=3) to your JSON 
5. If all else fails (specifically #3,#4) try[ this json file](https://github.com/sp614x/optifine/issues/1825#issuecomment-424065772) out.

Good luck!

**Comment by H4kt** [comment]
Mojang launcher seems to have no issues when launching it

**Comment by AarushX** [comment]
I think Mojang's Launcher has a few automatic features that you need to do here manually. Have you tried 4?

**Comment by H4kt** [comment]
They are indeed in the json file I've attached
![image](https://user-images.githubusercontent.com/50774419/180509999-4302c5eb-bb9e-40a7-b065-014efcf0d14d.png)

**Comment by AarushX** [comment]
Honestly from what I can tell (I don't have time to go through a 1606 line json) you should / could be fine. The issue wouldn't be with the JSON and instead the folder you're launching from (it could be downloading the assets to a different folder?) 
[This could help](https://github.com/sp614x/optifine/issues/1635) but otherwise good luck!

**Comment by H4kt** [comment]
Bruh like a you serious?
The JSON file is completely fine cuz it was tested on Mojang's launcher.
Your library is definitely working incorrectly in that case.

**Comment by AarushX** [comment]
> Bruh like a you serious? 

I'm sorry-- I'm just trying to figure out what could be going wrong. 
You mentioned the MCL can launch it but your launcher can't. Check out the documentation for MCLC and try overriding certain settings... but it **should** be launching. 

Take this with a pinch of salt, since I don't know too much about this specifically, but maybe try changing your custom libs to the same format as everything else.

![image](https://user-images.githubusercontent.com/36015585/180514723-7e376ee8-a56c-4b05-a5b6-476df8293608.png)

**Comment by AarushX** [comment]
Also since we've established this as a launcher issue consider joining the [MCLC discord.](https://discord.gg/mvr7pT78) Pierce is fast at responding to most things.

**Comment by Pierce01** [comment]
Hey there H4kt, I'll take a look into why MCLC isn't launching with your specified launch options. I apologize for the delay in response, it's been a busy week.

Aarush, I appreciate you trying to help, but if you don't know what the issue is and are unwilling to test it, please don't continue to provide solutions as it's just going to cause confusion to others reading this thread.

**Comment by Pierce01** [comment]
Hey [H4kt](https://github.com/H4kt), would you be able to join the Discord and shoot me a message? I'd like to collect more information so I can work on this issue.

If you don't want to join the discord, my tag is **Pierce#2657**.
