### ISSUE TITLE
Error starting optifine or custom Jar

### ISSUE THREAD

**Issue by leoms1408** [Pierce01/MinecraftLauncher-core#99]
When I start a custom jar file, I get the following error.

`2023-01-15 01:02:26,846 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2023-01-15 01:02:26,852 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[01:02:27] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
    at java.util.StringTokenizer.<init>(StringTokenizer.java:199) ~[?:1.8.0_51]
    at java.util.StringTokenizer.<init>(StringTokenizer.java:221) ~[?:1.8.0_51]
    at joptsimple.ArgumentAcceptingOptionSpec.addArguments(ArgumentAcceptingOptionSpec.java:263) ~[ArgumentAcceptingOptionSpec.class:?]
    at joptsimple.RequiredArgumentOptionSpec.detectOptionArgument(RequiredArgumentOptionSpec.java:50) ~[RequiredArgumentOptionSpec.class:?]
    at joptsimple.ArgumentAcceptingOptionSpec.handleOption(ArgumentAcceptingOptionSpec.java:257) ~[ArgumentAcceptingOptionSpec.class:?]
    at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:513) ~[OptionParser.class:?]
    at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56) ~[OptionParserState$2.class:?]
    at joptsimple.OptionParser.parse(OptionParser.java:396) ~[OptionParser.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:79) ~[Main.class:?]
    ... 6 more`

and when I try to start a plain optifine 1.19.2 installation, I get this error

`[MCLC]: Failed to start due to TypeError: Cannot read properties of undefined (reading 'url'), closing...`

**Comment by leoms1408** [comment]
Still have the problem, any ideas?

**Comment by Pierce01** [comment]
Mind posting your version json? Also, how did you install optifine?

**Comment by Pierce01** [comment]
Please reopen this issue once you send the version json you were using.
